name: Update Algolia Index
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "docs/**"
      - "scripts/algolia.ts"
      - ".github/workflows/algolia.yaml"

env:
  ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
  ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
  NODE_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install
      # TODO - can move to be a part of app.yaml in the future
      # this retains the property of 1-1 relation between top level directory and .github/workflows
      - name: Update Algolia Index
        run: ts-node scripts/algolia.ts
