name: Publish Web App
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "app/**"
      - "docs/**"
      - ".github/workflows/app.yaml"

env:
  API_URL: https://api.samepage.network
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  CLERK_FRONTEND_API: clerk.samepage.network
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
  CONVERTKIT_API_KEY: ${{ secrets.CONVERTKIT_API_KEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  IS_PRODUCTION: 1
  ORIGIN: https://samepage.network
  ROADMAP_ROAM_TOKEN: ${{ secrets.ROADMAP_ROAM_TOKEN }}
  STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  WEB_SOCKET_URL: https://ws.samepage.network
  WEB3_STORAGE_API_KEY: ${{ secrets.WEB3_STORAGE_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install
      - name: build
        run: npx ts-node scripts/cli.ts build
      - name: deploy
        run: npx ts-node scripts/cli.ts deploy
