name: Publish Data Infrastructure
on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - AWS_MIGRATION
    paths:
      # We need the gh action to somehow watch for new files inserted in api
      - "data/**"
      - ".github/workflows/data.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  CONVERTKIT_API_KEY: ${{ secrets.CONVERTKIT_API_KEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
  IS_PRODUCTION: 1
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install --force
      - name: plan
        run: npx fuego plan
      # temporary hack until I figure out better planetscale workflows
      - name: hack
        run: rm out/apply-sql.txt
      - name: apply
        run: npx fuego apply
        env:
            NODE_ENV: production
