name: Publish Data Infrastructure
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - AWS_MIGRATION
    paths:
      - "data/**"
      - ".github/workflows/data.yaml"
      - "scripts/commands/plan.ts"
      - "scripts/commands/apply.ts"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  CONVERTKIT_API_KEY: ${{ secrets.CONVERTKIT_API_KEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
  IS_PRODUCTION: 1
  ROAMJS_GITHUB_TOKEN: ${{ secrets.ROAMJS_GITHUB_TOKEN }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # TODO - when this issue resolves, remove
      # https://github.com/TypeStrong/ts-node/issues/2094
      - uses: actions/setup-node@v4
        with:
          node-version: 18.18.2
      - name: install
        run: npm install --force
      - name: plan
        run: npx ts-node scripts/cli.ts plan
      # temporary hack until I figure out better planetscale workflows
      - name: hack
        run: rm out/migrations/apply.sql
      - name: apply
        run: npx ts-node scripts/cli.ts apply --tf
        env:
          NODE_ENV: production
