name: Publish NPM Package
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "package/**"
      - scripts/commands/package.ts
      - ".github/workflows/package.yaml"

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install
      - name: package
        run: npx ts-node scripts/cli.ts package
      # TODO - move all below to npx ts-node scripts/cli.  
      - name: publish
        run: npm publish --access public
        working-directory: dist/internal
      - name: publish
        run: npm publish --access public
        working-directory: dist/external
      - name: publish
        run: npm publish --access public
        working-directory: dist/testing
      - name: publish
        run: npm publish --access public
        working-directory: dist/scripts
      - name: publish
        run: npm publish --access public
        working-directory: dist
      - name: Set version
        run: echo "VERSION=$(cat package.json | grep version | cut -d '"' -f 4)" >> $GITHUB_ENV
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
