name: Publish NPM Package
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "package/**"
      - scripts/commands/package.ts
      - ".github/workflows/package.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install
      - name: package
        run: npx ts-node scripts/cli.ts package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: publish
        run: npx ts-node scripts/cli.ts publish
        env:
          GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
