name: Publish NPM Package
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "package/**"
      - ".github/workflows/package.yaml"

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install
      - name: package
        run: node scripts/package.js
      - name: publish
        run: npm publish --access public
        working-directory: dist/internal
      - name: publish
        run: npm publish --access public
        working-directory: dist/external
      - name: publish
        run: npm publish --access public
        working-directory: dist/testing
      - name: publish
        run: npm publish --access public
        working-directory: dist/scripts
      - name: publish
        run: npm publish --access public
        working-directory: dist
      - name: Conventional Changelog Action
        id: changelog 
        uses: TriPSs/conventional-changelog-action@v3 
        with: 
          github-token: ${{ secrets.TERRAFORM_GITHUB_TOKEN } 
          output-file: "false" 
      - name: Create Release 
        uses: actions/create-release@v1 
        if: ${{ steps.changelog.outputs.skipped == 'false' } 
        env: 
          GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }} 
          body: ${{ steps.changelog.outputs.clean_changelog }}
